apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bulk-import-1732626072990
  annotations:
    github.com/project-slug: cloud-eda/bulk-import-1732626072990
spec:
  type: other
  lifecycle: unknown
  owner: user:default/cyber-stalker-bit
